# Generated by Django 2.2.28 on 2022-09-26 14:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=200)),
                ('detalle', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bibliografia', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='', upload_to='alimentacion')),
            ],
            options={
                'verbose_name': 'Alimentacion',
                'verbose_name_plural': 'Alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=200)),
                ('detalle', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bibliografia', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='', upload_to='alojamiento')),
            ],
            options={
                'verbose_name': 'Alojamiento',
                'verbose_name_plural': 'Alojamiento',
            },
        ),
        migrations.CreateModel(
            name='caballo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('caracter', models.TextField(max_length=100)),
                ('salud', models.TextField(max_length=100)),
                ('altura', models.TextField(max_length=100)),
                ('peso', models.TextField(max_length=100)),
                ('observaciones', models.TextField(max_length=150)),
                ('tipo', models.CharField(choices=[('sangre caliente', 'sangre caliente'), ('sangre fria', 'sangre fria'), ('sangre templada', 'sangre templada'), ('pony', 'pony'), ('pura sangre', 'sangre templada'), ('barroco', 'barroco')], default='sangre caliente', max_length=50)),
                ('imagen', models.ImageField(default='', upload_to='caballo')),
            ],
            options={
                'verbose_name': 'Caballo',
                'verbose_name_plural': 'Caballo',
            },
        ),
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=200)),
                ('detalle', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bibliografia', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='', upload_to='consejos')),
                ('keyword', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Consejos',
                'verbose_name_plural': 'Consejos',
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=200)),
                ('detalle', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bibliografia', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='', upload_to='entrenamiento')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamiento',
            },
        ),
        migrations.CreateModel(
            name='gato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('caracter', models.TextField(max_length=100)),
                ('salud', models.TextField(max_length=100)),
                ('altura', models.TextField(max_length=100)),
                ('peso', models.TextField(max_length=100)),
                ('observaciones', models.TextField(max_length=150)),
                ('tipo', models.CharField(choices=[('pelo largo', 'pelo largo'), ('pelo mediano', 'pelo mediano'), ('pelo corto', 'pelo corto')], default='pelo largo', max_length=50)),
                ('imagen', models.ImageField(default='', upload_to='gato')),
            ],
            options={
                'verbose_name': 'Gato',
                'verbose_name_plural': 'Gato',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=200)),
                ('detalle', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bibliografia', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='', upload_to='legal')),
            ],
            options={
                'verbose_name': 'Legal',
                'verbose_name_plural': 'Legal',
            },
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=200)),
                ('detalle', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bibliografia', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='', upload_to='otros')),
            ],
            options={
                'verbose_name': 'Otros',
                'verbose_name_plural': 'Otros',
            },
        ),
        migrations.CreateModel(
            name='perro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('caracter', models.TextField(max_length=100)),
                ('salud', models.TextField(max_length=100)),
                ('altura', models.TextField(max_length=100)),
                ('peso', models.TextField(max_length=100)),
                ('observaciones', models.TextField(max_length=150)),
                ('tipo', models.CharField(choices=[('grande', 'grande'), ('mediano', 'mediano'), ('pequeño', 'pequeño')], default='grande', max_length=50)),
                ('imagen', models.ImageField(default='', upload_to='perro')),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perro',
            },
        ),
        migrations.CreateModel(
            name='Sanitario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=200)),
                ('detalle', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bibliografia', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='', upload_to='sanitario')),
            ],
            options={
                'verbose_name': 'Sanitarios',
                'verbose_name_plural': 'Sanitarios',
            },
        ),
    ]
