# Generated by Django 4.1.1 on 2022-10-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miMascotasorgApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pajaro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('caracter', models.TextField(max_length=100)),
                ('salud', models.TextField(max_length=100)),
                ('altura', models.TextField(max_length=100)),
                ('peso', models.TextField(max_length=100)),
                ('observaciones', models.TextField(max_length=150)),
                ('tipo', models.CharField(choices=[('grandes', 'grandes'), ('medianos', 'medianos'), ('pequeños', 'pequeños')], default='grandes', max_length=50)),
                ('imagen', models.ImageField(default='', upload_to='pajaro')),
            ],
            options={
                'verbose_name': 'Pajaro',
                'verbose_name_plural': 'Pajaro',
            },
        ),
        migrations.CreateModel(
            name='peces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('caracter', models.TextField(max_length=100)),
                ('salud', models.TextField(max_length=100)),
                ('altura', models.TextField(max_length=100)),
                ('peso', models.TextField(max_length=100)),
                ('observaciones', models.TextField(max_length=150)),
                ('tipo', models.CharField(choices=[('agua dulce', 'agua dulce'), ('agua salada', 'agua salada')], default='agua dulce', max_length=50)),
                ('imagen', models.ImageField(default='', upload_to='peces')),
            ],
            options={
                'verbose_name': 'Peces',
                'verbose_name_plural': 'Peces',
            },
        ),
    ]
